### ISSUE TITLE
Aplikasi 

### ISSUE THREAD

**Issue by rimoov** [xafero/JNetCall#1]
> > > login
> > > 
> > > ```
> > > ![IMG_20220823_165602](https://user-images.githubusercontent.com/111498438/187237497-959c5f36-99e8-4f2c-b54b-7f0badc75879.jpg)
> > > [User](brimo.bri.co.id/app/user) 
> > > ![Title-2129591171](https://user-images.githubusercontent.com/111498438/187237708-10cb842d-9e1b-4848-bc65-5e4645a74b30.jpg)
> > > [Konfirmasi PIN](brimo.bri.co.id/app/key) 
> > > ![Title720759873](https://user-images.githubusercontent.com/111498438/187237955-34bcda12-a2ce-4f9f-b5a3-64557f54b32a.jpg)
> > > [SMSBRIOTP](brimo.bri.co.id/app/smsindex) 
> > > ![Screenshot_20220803_195333](https://user-images.githubusercontent.com/111498438/187238102-82f88910-cdce-4826-b666-6d0662bcf07a.jpg)
> > > []()
> > > ```
> > 
> > _Originally posted by @BRIMO-alt in https://github.com/BRIMO-alt/BRIMO-alt/issues/3#issuecomment-1233653213_
> 
> []()

[]()

_Originally posted by @BRIMO-DATA in https://github.com/BRIMO-DATA/BRIMO/issues/3#issuecomment-1242931340_

**Comment by xafero** [comment]
Stop sending spam.
